### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Byxs20** [ZJU-lishuang/yolov5_sim#1]
Traceback (most recent call last):
  File ".\detect_single.py", line 139, in <module>
    detect_test()
  File ".\detect_single.py", line 51, in detect_test
    model = torch.load(weights, map_location=device)['model'].float().eval()
  File "C:\Users\Byxs20\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Byxs20\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by ZJU-lishuang** [comment]
Maybe the pytorch version problem?

**Comment by Byxs20** [comment]
原来如此 pytorch version == 1.9.0 cuda11.1

**Comment by Byxs20** [comment]
torch-1.8.0+cu111-cp38-cp38-win_amd64
torchvision-0.9.0+cu111-cp38-cp38-win_amd64
torchaudio-0.8.0-cp38-none-win_amd64


Traceback (most recent call last):
  File ".\detect_single.py", line 139, in <module>
    detect_test()
  File ".\detect_single.py", line 51, in detect_test
    model = torch.load(weights, map_location=device)['model'].float().eval()
  File "E:\yolov5_sim\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "E:\yolov5_sim\lib\site-packages\torch\serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

又出现了同样的报错
请问作者用的是那个版本

**Comment by ZJU-lishuang** [comment]
好像是1.6版本，没必要在这上面浪费时间，简单看看代码应该自己就能在YOLOv5的基础上简化出来同样的东西 在2021年09月19日 07:44，Byxs20 写道： torch-1.8.0+cu111-cp38-cp38-win_amd64 torchvision-0.9.0+cu111-cp38-cp38-win_amd64 torchaudio-0.8.0-cp38-none-win_amd64 Traceback (most recent call last): File ".\detect_single.py", line 139, in detect_test() File ".\detect_single.py", line 51, in detect_test model = torch.load(weights, map_location=device)['model'].float().eval() File "E:\yolov5_sim\lib\site-packages\torch\serialization.py", line 593, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "E:\yolov5_sim\lib\site-packages\torch\serialization.py", line 762, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'v'. 又出现了同样的报错 请问作者用的是那个版本 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Byxs20** [comment]
好的，感谢
